export const ORGANISM_TEMPLATES = [
  {
    id: 'customer_pulse',
    icon: '📨',
    name: 'Customer Pulse',
    goal: 'Watch every customer email, route urgent ones to humans, draft replies for the rest.',
    constraints: ['respond within 5 minutes', 'never auto-reply to billing'],
    forbidden: ['share PII', 'make pricing promises'],
    suggested_sources: [
      { kind: 'webhook', type: 'email_received' },
      { kind: 'interval', type: 'health_check', interval_s: 300 },
    ],
    suggested_mcp: ['filesystem', 'fetch'],
  },
  {
    id: 'repo_sentinel',
    icon: '👁',
    name: 'Repo Sentinel',
    seedName: 'Governed repo maintainer',
    goal: 'Read the configured GitHub repository, inspect the project structure and available contents, identify practical ways to improve the project, and suggest findings in Slack. Do not edit files, create pull requests, open issues, merge code, or make repository changes.',
    constraints: [
      'prefer reversible and observable actions',
      'read repository contents before making recommendations',
      'send improvement suggestions to Slack only through approval-gated messaging',
      'record reasoning, alternatives, and results for audit',
      'escalate risky actions to human approval',
    ],
    forbidden: ['edit repository files', 'create pull requests', 'open or close issues', 'merge code', 'post comments without approval'],
    suggested_sources: [
      {
        kind: 'github_repo',
        type: 'repo_maintainer_signal',
        interval_s: 1,
        requires_approval: true,
        no_fake_activity: true,
        write_connectors: ['slack_webhook_message'],
        lifecycle: {
          mode: 'one_shot',
          terminate_on: 'declare_done',
          reason: 'Repo improvement demo stops after the approved Slack suggestion is delivered.',
        },
      },
    ],
    suggested_mcp: ['github'],
  },
  {
    id: 'market_dreamer',
    icon: '📈',
    name: 'Market Dreamer',
    goal: 'Poll a price feed, dream worst-case scenarios, alert on anomalies.',
    constraints: ['alert only on >2-sigma moves', 'cool down 10 min after alert'],
    forbidden: ['execute trades'],
    suggested_sources: [
      { kind: 'http_poll', type: 'price_tick', interval_s: 60,
        url: 'https://api.example.com/price' },
    ],
    suggested_mcp: ['fetch'],
  },
  {
    id: 'blank',
    icon: '🌱',
    name: 'Blank slate',
    goal: '',
    constraints: [], forbidden: [],
    suggested_sources: [], suggested_mcp: [],
  },
]
